# Generated by Django 5.1.9 on 2025-06-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosterceros',
            name='vendedor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
